version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aiwal-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./vendor:/var/www/html/vendor
    networks:
      - aiwal-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: aiwal-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - aiwal-network

  nginx:
    image: nginx:alpine
    container_name: aiwal-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - aiwal-network
    depends_on:
      - app

  npm:
    image: node:latest
    container_name: aiwal-npm
    volumes:
      - ./:/var/www/html
      - node_modules:/var/www/html/node_modules
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - aiwal-network

networks:
  aiwal-network:
    driver: bridge

volumes:
  mysql-data:
  node_modules: